### ISSUE TITLE
Support for ALTO 3.0, 4.0 etc. in alto2hocr

### ISSUE THREAD

**Issue by zuphilip** [filak/hOCR-to-ALTO#13]
Can we also support ALTO 3.0, 4.0 etc. in the transformation alto2hocr? I am not speaking about any new functionalities but just the new namespaces. The transformation alto2text is using a different syntax e.g.
```xslt
<xsl:template match="*[local-name()='TextLine']">
```
instead of
```xslt
<xsl:template match="TextLine">
```
and thereby is already compatible with other versions of the ALTO namespace. Maybe we can do something similar for the alto2hocr transformation.

See also https://github.com/UB-Mannheim/ocr-fileformat/issues/95

**Comment by filak** [comment]
Yes, but unfortunately I do not have time right now... I will try to look at it by the end of this month.

**Comment by filak** [comment]
Fixed with 100e937

**Comment by zuphilip** [comment]
The commit you mentioned added a new hocr2alto3.0.xsl, but the other direction which I asked here, i.e. that alto2hocr also supports alto v3.0, 4.0 etc, is still not possible. Therefore, I wanted to ask, if we can reopen this issue.

**Comment by filak** [comment]
Fixed with 5122b72ed1c6c9a6a5582a0554e45ddc658b68df

Feedback is welcome !
